[features]
seeds = false
skip-lint = false

[programs.devnet]
agritrust_escrow = "B9UVTiJQx8ftRob2oFQ5gSGQB6yraPX5UjAczyvqSYEU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -r tsx/register tests/escrow.test.ts --timeout 1000000"
